#! python
import os
import sys


def arguments_parser(args):
    """
    Return only the path for now.
    """
    print("Script's file name: ", args[0])
    print("Number of arguments: ", len(args))
    counter = 0
    for arg in args:
        counter += 1
        if arg.find("/"):
            print("Found the path")
            return arg
        print_str = " Argument index[{0}] : {1}".format(counter, arg)
        print(print_str)
        # print("Argument index[%d] : %s" % (counter, arg))
    return 0


# Get the arguments passed in at the command line.
if len(sys.argv) > 1:
    path = arguments_parser(sys.argv[1:])  # pass just the args
    full_path = path + ".py"
    if os.path.exists(full_path):
        print("This is the path:", full_path)
    else:
        #  TODO: throw an exception here
        print("Thrown exception: path does not exist:", full_path)

    # Run the file.
    try:
        command_module = __import__("%s" % path)
    except ImportError:
        #  TODO: throw an exception here
        print("Thrown exception error: unable to __import__")

    print("Hello, world!")


