from ui import UI
from ui.low.job_icon import JobIcon
from tool.generators.generator import gen_key

__author__ = 'John Underwood'


class JobCreateIcon(UI):
    """
    Create an input control (I-CON) and then check database for
    correct values.
    """
    JobIcon()
    unique = gen_key()
    runtime = {
        'new': ('Click', 'css=#control-list>ul>li.active>a',),
        'iConName': ('Type', '#control_name', 'Automated ' + unique),
        'iConDesc': ('Type', '#control_description', 'Auto-generated by QA'),
        'iConType': (
            'Select', '#job_description_control_type_id', 'Single Select'),
        'internal': ('Click', 'css=#control-editor>div:nth-child(11)>'
                              'label:nth-child(6)', ),
        'addNewOption': ('Click', 'css=#control-editor>div:nth-child(11)>'
                                  'div:nth-child(7)>div:nth-child(2)>a', ),
    }
    process = UI()
    process.update(runtime)
    order = ('new', 'iConName', 'iConDesc', 'iConType', 'internal',
             'addNewOption')
    process.execute(order)
    process.wait(1)
    process.teardown()

